spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms_vue?useSSL=false
    username: root
    password: ab123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_spl: true
server:
  port: 8181
